# Generated by Django 4.1.6 on 2023-06-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0028_announcements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='announcements_id',
            new_name='announcement_id',
        ),
    ]
